List iconCastom = [
  {"icon": "assets/icons/icon1.png", "name": "كهرباء"},
  {"icon": "assets/icons/icon2.png", "name": "TV"},
  {"icon": "assets/icons/icon3.png", "name": "تكييفات"},
  {"icon": "assets/icons/12.png", "name": 'الخياطة'},
  {"icon": "assets/icons/icon4.png", "name": "تنظيف"},
  {"icon": "assets/icons/16.png", "name": 'التصوير'},
  {"icon": "assets/icons/18.png", "name": 'الحلاقة'},
  {"icon": "assets/icons/icon5.png", "name": "دهانات"},
  {"icon": "assets/icons/11.png", "name": 'الحدادة'},
  {"icon": "assets/icons/icon6.png", "name": "غسالات"},
  {"icon": "assets/icons/icon7.png", "name": "سباكة"},
  {"icon": "assets/icons/icon8.png", "name": "كهرباء"},
  {"icon": "assets/icons/icon9.png", "name": "صرف"},
  {"icon": "assets/icons/10.png", "name": 'النجارة'},
  {"icon": "assets/icons/13.png", "name": 'الخزف والفخار'},
  {"icon": "assets/icons/14.png", "name": 'العمارة والبناء'},
  {"icon": "assets/icons/15.png", "name": 'ميكانيكا'},
  {"icon": "assets/icons/17.png", "name": 'الطبخ'},
  {"icon": "assets/icons/19.png", "name": 'الزجاج '},
];

const List<String> iconCastomCraft = <String>[
  'كهرباء',
  'TV',
  'تكييفات',
  'تنظيف',
  'دهانات',
  'غسالات',
  'سباكة',
  'صرف',
  'النجارة',
  'الحدادة',
  'الخياطة',
  'الخزف والفخار',
  'العمارة والبناء',
  'ميكانيكا السيارات',
  'التصوير',
  'الطبخ',
  'الحلاقة',
  'الزجاج ',
];
